import { Inter } from "next/font/google";
import "./globals.css";

// Importing local CSS files
import '@/assets/css/fontawesome.css';
import '@/assets/css/owl.css';
import '@/assets/css/animate.css';
import '@/assets/css/modal_animation.css';
import '@/vendor/bootstrap/css/bootstrap.min.css';
import '@/assets/dropdown/jquery.sweet-dropdown.min.css';
import '@/assets/css/templatemo-cyborg-gaming.css';

import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Squad Groups</title>

        {/* External CSS */}
        <link
          href="https://unpkg.com/swiper/swiper-bundle.min.css"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.2/css/fontawesome.min.css"
          integrity="sha384-BY+fdrpOd3gfeRvTSMT+VUZmA728cfF9Z2G42xpaRkUGu2i3DyzpTURDo5A6CaLK"
          crossOrigin="anonymous"
        />
      </head>
      <body className={inter.className}>
        {children}

        {/* External JS, loaded after page load */}
        <Script src="https://code.jquery.com/jquery-3.5.1.min.js" strategy="afterInteractive" />
        <Script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" strategy="afterInteractive" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" strategy="afterInteractive" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" strategy="afterInteractive" />
        <Script src="https://unpkg.com/swiper/swiper-bundle.min.js" strategy="afterInteractive" />
        <Script src="https://cdn.jsdelivr.net/npm/@simondmc/popup-js@1.4.2/popup.min.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
